### ISSUE TITLE
No outputs for FAST5, sequencing_summary.txt 

### ISSUE THREAD

**Issue by jonperdomo** [WGLab/LongReadSum#13]
No output is generated for FAST5 files containing single or multiple datasets:

<img width="242" alt="image" src="https://user-images.githubusercontent.com/14855676/172704887-4ed951b8-842f-46f7-877c-5e4795d883c8.png">

**Comment by jonperdomo** [comment]
I also tried using the sequencing_summary.txt file as the input with the same result. This file produces results with PycoQC and MinIONQC so it does not appear to be an issue with the file:

![image](https://user-images.githubusercontent.com/14855676/174852026-45618d6f-590f-4a66-aef9-e004eff24522.png)

**Comment by liuqianhn** [comment]
@jonperdomo sequencing_summary.txt might be different for various basecallers. Please check the format (sequencing_summary.txt) with the code to see how to improve it.

**Comment by jonperdomo** [comment]
Unthreaded implementation is complete.
