### ISSUE TITLE
cite publication

### ISSUE THREAD

**Issue by danielecook** [WGLab/LongReadSum#22]
The readme states to cite the publication below but none is listed. Does LongReadSum have an associated publication?

**Comment by jonperdomo** [comment]
Hi Daniel, I will be presenting this work at ASHG this year and have updated a citation file to our main page in commit cc02f64d2dc5067baeb57381c1ec9b38349e1af1

**Comment by jonperdomo** [comment]
I have also updated the the README with the same citation
