### ISSUE TITLE
Issue with running LongReadSum

### ISSUE THREAD

**Issue by doshirLV** [WGLab/LongReadSum#44]
Hi WGLab developers,

I received the following error when running the tool:
Total number of bases is not consistent.
ERROR:root:Completed with errors.

It is weird because these are new/different samples that I am processing when I ran into the error, but I have previously ran the tool with no issues before (same nucleic acid type, sequencer, and input data type). My command was: `python ~/tools/LongReadSum fq -i pass.ND1.fastq -o read_summary.`

Thank you for the help,
Raj

**Comment by jonperdomo** [comment]
Hi, can you let us know which version you are using, and possibly an example file so I can try to reproduce the error?

**Comment by doshirLV** [comment]
Hello,

How can I check the version number?
Also because this is private data, I am unable to provide an example file.

Thanks,
Raj

**Comment by jonperdomo** [comment]
It's recommended to download the latest release version: https://github.com/WGLab/LongReadSum/releases/tag/v1.2.0
If you installed via docker, please pull the latest release image specifying the version number:
`docker pull genomicslab/longreadsum:v1.2.0`

I will look into how this error may have occurred.

**Comment by doshirLV** [comment]
Okay, I reinstalled it by cloning the GitHub repo and running make.
Let me know if there is any other information I can provide you to help investigate the cause of this.

Much appreciated

**Comment by jonperdomo** [comment]
Okay I fixed a possible issue. Please pull the latest commit from the **main** branch,  run make, and see if the issue is resolved.

**Comment by doshirLV** [comment]
Hope you had a great weekend Jonathan,

This fixed the issue. I was able to run it and get an output.
Thank you so much for your promptness on this matter!

Cheers,
Raj

**Comment by jonperdomo** [comment]
Hi Raj, no problem, happy to hear!
