### ISSUE TITLE
--help output

### ISSUE THREAD

**Issue by gchevignon** [WGLab/LongReadSum#57]
Hello,
Your help message is missing so much information ...
What is :
-i
-I
-P
-t
--csv
--input
--output
--threads
I know some of these parameters are quite obvious, but please ...
Seeing this help message, I am afraid some parameters are completely missing from the readme or --help ...?

**Comment by jonperdomo** [comment]
I will update this soon, this is an error in which the common filetype parameters did not show up in the help text. Thank you.
